version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10.12
    commands:
      - pip install poetry
      - poetry install
  pre_build:
    commands:
      - SECRET_KEY=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query SECRET_KEY --output text --region us-east-1)
      - export SECRET_KEY
      - DB_NAME=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query DB_NAME --output text --region us-east-1)
      - export DB_NAME
      - DB_USER=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query DB_USER --output text --region us-east-1)
      - export DB_USER
      - DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query DB_PASSWORD --output text --region us-east-1)
      - export DB_PASSWORD
      - DB_HOST=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query DB_HOST_OUTER --output text --region us-east-1)
      - export DB_HOST
      - export DJANGO_SETTINGS_MODULE="botify.settings"
      - cd botify/
      - poetry run python manage.py migrate
      - poetry run python manage.py collectstatic --noinput
  build:
    commands:
      - SECRET_KEY=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query SECRET_KEY --output text --region us-east-1)
      - echo $SECRET_KEY
      - export SECRET_KEY
      - DB_NAME=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query DB_NAME --output text --region us-east-1)
      - export DB_NAME
      - DB_USER=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query DB_USER --output text --region us-east-1)
      - export DB_USER
      - DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query DB_PASSWORD --output text --region us-east-1)
      - export DB_PASSWORD
      - DB_HOST=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query DB_HOST_OUTER --output text --region us-east-1)
      - echo $DB_HOST
      - export DB_HOST
      - export DJANGO_SETTINGS_MODULE="botify.settings"
      - cd botify/
      - poetry run python manage.py test
artifacts:
  files:
    - '**/*'
  base-directory: .