version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10.12
    commands:
      - pip install poetry
      - poetry install
  build:
    commands:
      - SECRET_KEY=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query SecretString --output text --region us-east-1)
      - SECRET_KEY=$(echo $SECRET_STRING | jq -r .SECRET_KEY)
      - export SECRET_KEY
      - echo $SECRET_KEY
      - DB_NAME=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query SecretString --output text --region us-east-1)
      - DB_NAME=$(echo $DB_NAME | jq -r .DB_NAME)
      - export DB_NAME
      - DB_USER=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query SecretString --output text --region us-east-1)
      - DB_USER=$(echo $DB_USER | jq -r .DB_USER)
      - export DB_USER
      - DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query SecretString --output text --region us-east-1)
      - DB_PASSWORD=$(echo $DB_PASSWORD | jq -r .DB_PASSWORD)
      - export DB_PASSWORD
      - DB_HOST=$(aws secretsmanager get-secret-value --secret-id botifyapp-secrets --query SecretString --output text --region us-east-1)
      - DB_HOST=$(echo $DB_HOST | jq -r .DB_HOST_OUTER)
      - echo $DB_HOST
      - export DB_HOST
      - export DJANGO_SETTINGS_MODULE="botify.settings"
      - cd botify/
      - poetry run python manage.py migrate
      - poetry run python manage.py collectstatic --noinput
      - poetry run python manage.py test
artifacts:
  files:
    - '**/*'
  base-directory: .