version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - api
    networks:
      - botify
    volumes:
      - static:/home/ubuntu/app/botify/botify/static/
      - /etc/letsencrypt:/etc/letsencrypt
  api:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=botify.production_settings
    command: >
      sh -c "
              python manage.py migrate && python manage.py collectstatic --noinput &&
              gunicorn botify.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/botify/
      - static:/usr/src/botify/botify/static/
    expose:
      - 8000
    networks:
      - botify

networks:
  botify:
    driver: bridge

volumes:
  static:


