# Generated by Django 5.0.2 on 2024-04-09 17:35

import songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_add_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='thumbnail_height', null=True, upload_to=songs.models.thumbnail_directory_path, width_field='thumbnail_width'),
        ),
        migrations.AddField(
            model_name='song',
            name='thumbnail_height',
            field=models.IntegerField(default=720),
        ),
        migrations.AddField(
            model_name='song',
            name='thumbnail_width',
            field=models.IntegerField(default=1280),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to=songs.models.songs_directory_path),
        ),
    ]
