# Generated by Django 5.0.2 on 2024-05-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_add_comment_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
    ]
