# Generated by Django 5.0.2 on 2024-06-06 17:40

import django.db.models.deletion
import songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, height_field='thumbnail_height', null=True, upload_to=songs.models.thumbnail_temp_directory_path, width_field='thumbnail_width')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
        ),
    ]
