# Generated by Django 5.0.2 on 2024-06-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_create_temp_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempthumbnail',
            name='thumbnail_height',
            field=models.IntegerField(default=720),
        ),
        migrations.AddField(
            model_name='tempthumbnail',
            name='thumbnail_width',
            field=models.IntegerField(default=1280),
        ),
    ]
